import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";

import "./globals.css";
import "@uswds/uswds/css/uswds.min.css";
import "@trussworks/react-uswds/lib/index.css";

import {
  GovBanner,
} from "@trussworks/react-uswds";
import AppHeader from "./ui/components/AppHeader";
import AppFooter from "./ui/components/AppFooter";
import AppHeaderSimple from "./ui/components/AppHeaderSimple";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GovBanner />
        <AppHeaderSimple />
            {children}
        {/* <AppFooter /> */}
      </body>
    </html>
  );
}
